#  What does Pandas stand for?
-Python Data Analysis Library
#  What are the 2 collections used in Pandas
- series, dataframe
#  Name 4 things Pandas can do for us
- data cleansing, data normalization, data visualization, data inspection
# To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?
-df.sort_VALUES
# What is a CSV?
-useful for handling structured data without the complexity of proprietary file formats
# When cleaning data what values do we not like in our data?
- outliners 

In [1]:
#Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2).
# You can use the reshape method -- `.reshape()`

import numpy as np


original_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
reshaped_array = original_array.reshape(2, 3, 2)

print("Original array:")
print(original_array)
print("Reshaped array:")
print(reshaped_array)

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [18]:
#8. Use NumPy `.linspace()` to create an array with 6 linearly spaced values between 0 and 20

import numpy as np


linear_array = np.linspace(0, 20, 6)

print(linear_array)

[ 0.  4.  8. 12. 16. 20.]


In [17]:
#Make a Deep Copy of the above array

import numpy as np
import copy


linear_array = np.linspace(0, 20, 6)
deep_copy_array = copy.deepcopy(linear_array)

print("Original array:")
print(linear_array)
print("Deep copy array:")
print(deep_copy_array)


Original array:
[ 0.  4.  8. 12. 16. 20.]
Deep copy array:
[ 0.  4.  8. 12. 16. 20.]


In [19]:
#concatenate these 3 arrays into a new array named 'newArray'...
#    ```python
#            ([[25, 16]])
#            ([[11, 2], [13, 4]])
#            ([[7, 81], [5, 6], [11, 12]])
#    ```

import numpy as np


array1 = np.array([[25, 16]])
array2 = np.array([[11, 2], [13, 4]])
array3 = np.array([[7, 81], [5, 6], [11, 12]])
newArray = np.concatenate((array1, array2, array3), axis=0)

print(newArray)

[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [24]:
#Sort 'newArray' in order into 'sortedArray'

import numpy as np

newArray = np.array([[25, 16], [11, 2], [13, 4], [7, 81], [5, 6], [11, 12]])
sortedArray = np.sort(newArray, axis=0)

print(sortedArray)

[[ 5  2]
 [ 7  4]
 [11  6]
 [11 12]
 [13 16]
 [25 81]]


In [21]:
#Unpack the array tuples from the above 'reshapedArray'  into 4 well named variables. Print the 4 variables.

import numpy as np


reshapedArray = np.array([[[1, 2], [3, 4], [5, 6]],
                          [[7, 8], [9, 10], [11, 12]]])


(tuple1_1, tuple1_2, _), (tuple2_1, tuple2_2, _) = reshapedArray


print("Tuple 1:")
print(tuple1_1)
print(tuple1_2)
print("Tuple 2:")
print(tuple2_1)
print(tuple2_2)

Tuple 1:
[1 2]
[3 4]
Tuple 2:
[7 8]
[ 9 10]


In [22]:
#Combined and sort the following arrays into one called 'comboArray' ...
#    ```python
#        one = ([10, 11, 12, 13, 14, 15, 16, 17])
#        two = ([20, 21, 22, 23, 24, 25, 26, 27])
#        three = ([ 0, 1, 2, 3, 4, 5, 6, 7])
#    ```

import numpy as np


one = np.array([10, 11, 12, 13, 14, 15, 16, 17])
two = np.array([20, 21, 22, 23, 24, 25, 26, 27])
three = np.array([0, 1, 2, 3, 4, 5, 6, 7])
comboArray = np.concatenate((one, two, three))
sortedComboArray = np.sort(comboArray)

print(sortedComboArray)

[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [23]:
#Take 'comboArray' and perform the following slicing activities:
#    - print sec1 - the 2nd element
#    - print sec2 - all elements from the 3rd element to the last
#    - print sec3 - all elements from the 4th to the 14th elements
#    - print sec4 - the last 6 elements
#    - print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
#    - print sec6 - from #20 every even element to the end
#    - print sec7 - from the last element moving forward, every 5th element.

import numpy as np


comboArray = np.array([ 0,  1,  2,  3,  4,  5,  6,  7, 10, 11, 12, 13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 25, 26, 27])


sec1 = comboArray[1]
sec2 = comboArray[2:]
sec3 = comboArray[3:14]
sec4 = comboArray[-6:]
sec5 = comboArray[:16]
sec6 = comboArray[20::2]
sec7 = comboArray[-1::-5]


print("Section 1:", sec1)
print("Section 2:", sec2)
print("Section 3:", sec3)
print("Section 4:", sec4)
print("Section 5:", sec5)
print("Section 6:", sec6)
print("Section 7:", sec7)

Section 1: 1
Section 2: [ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
Section 3: [ 3  4  5  6  7 10 11 12 13 14 15]
Section 4: [22 23 24 25 26 27]
Section 5: [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17]
Section 6: [24 26]
Section 7: [27 22 15 10  3]


In [26]:
#Using `Series`, create a `DataFrame` that looks like this:
#    | Ingredients | Quantity | Unit |
#    |----|----|----|
#    | Flour | 4 | cups |
#    | Milk | 1 | cup |
#    | Eggs | 2 | large |
#    | Spam | 1 | can |
#    Name: Dinner, dtype: object

import pandas as pd


data = {
    'Ingredients': ['Flour', 'Milk', 'Eggs', 'Spam'],
    'Quantity': [4, 1, 2, 1],
    'Unit': ['cups', 'cup', 'large', 'can']
}
ingredients_series = pd.Series(data)

df = pd.DataFrame(ingredients_series)
df.index.name = 'Name'
df.columns = ['Dinner']

print(df)






                                Dinner
Name                                  
Ingredients  [Flour, Milk, Eggs, Spam]
Quantity                  [4, 1, 2, 1]
Unit           [cups, cup, large, can]


In [27]:
#16. Take this data and create a DataFrame named studentData
#    ```Python
#        {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
#            'Height': [5.1, 6.2, 5.1, 5.2],
#            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
#            'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
#            'Age': [21, 23, 24, 21],
#            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
#            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
#        }
#    ```

import pandas as pd

data = {
    'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
    'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
    'Age': [21, 23, 24, 21],
    'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
    'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
}

studentData = pd.DataFrame(data)

print(studentData)

      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket


In [28]:
#17. Add a new column to the DataFrame with the following deserts:
#        ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

import pandas as pd

data = {
    'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
    'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
    'Age': [21, 23, 24, 21],
    'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
    'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
}

studentData = pd.DataFrame(data)
desserts = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
studentData = studentData.assign(Desserts=desserts)

print(studentData)

      Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

       Desserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa  


In [29]:
#18. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

import pandas as pd

data = {
    'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
    'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
    'Age': [21, 23, 24, 21],
    'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
    'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket'],
    'Desserts': ['ice cream', 'Cashew Fudge', 'waffels', 'Carrot Halwa']
}

studentData = pd.DataFrame(data)
sorted_studentData = studentData.sort_values(by=['Name', 'address'], ascending=True)

print(sorted_studentData)

      Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

       Desserts  
3  Carrot Halwa  
2       waffels  
0     ice cream  
1  Cashew Fudge  


In [30]:
#19. Save this `DataFrame` here below to disc as a `.CSV` file with the name `cows_and_goats.csv`:
#
#    ```python
#        df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
#```

import pandas as pd


df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df.to_csv('cows_and_goats.csv')

print("DataFrame saved to 'cows_and_goats.csv'")


DataFrame saved to 'cows_and_goats.csv'


In [31]:
#20. (A) Using Pandas, make your own .CSV file with data on vegetables and save it.
#(B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

import pandas as pd

data = {
    'Vegetable': ['Carrot', 'Broccoli', 'Tomato', 'Spinach', 'Pepper'],
    'Color': ['Orange', 'Green', 'Red', 'Green', 'Red'],
    'Taste': ['Sweet', 'Nutty', 'Sour', 'Mild', 'Spicy']
}

vegetables_df = pd.DataFrame(data)
vegetables_df.to_csv('vegetables.csv', index=False)

print("Original DataFrame saved to 'vegetables.csv'")

Original DataFrame saved to 'vegetables.csv'
